package main

import (
	"context"
	"encoding/json"
	"log"
	"net/http"

	"github.com/bufbuild/connect-go"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	zyrevav1 "github.com/zyreva/zyreva/internal/gen/proto/zyreva/v1"        // generated by protoc-gen-go
	"github.com/zyreva/zyreva/internal/gen/proto/zyreva/v1/zyrevav1connect" // generated by protoc-gen-connect-go
	"github.com/zyreva/zyreva/internal/pkg/git"
	pack "github.com/zyreva/zyreva/internal/pkg/nixpacks"
)

type GitServer struct{}

func (s *GitServer) Clone(
	ctx context.Context,
	req *connect.Request[zyrevav1.CloneRequest],
) (*connect.Response[zyrevav1.CloneResponse], error) {
	log.Println("Request headers: ", req.Header())

	dest := git.Clone(req.Msg.Url)
	plan := pack.Build(dest)

	planStr, _ := json.Marshal(plan)

	res := connect.NewResponse(&zyrevav1.CloneResponse{
		Destination: string(planStr),
	})

	return res, nil
}

func main() {
	greeter := &GitServer{}
	mux := http.NewServeMux()
	path, handler := zyrevav1connect.NewGitServiceHandler(greeter)
	mux.Handle(path, handler)
	http.ListenAndServe(
		"localhost:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
