apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: zyreva
build:
  artifacts:
    - image: zyreva-server
      docker:
        dockerfile: crates/server/Dockerfile.skaffold
manifests:
  rawYaml:
    - .devcontainer/manifests/deployment.yaml
    - .devcontainer/manifests/buildkit.yaml
    - .devcontainer/manifests/registry.yaml
deploy:
  helm:
    releases:
    - name: db
      remoteChart: oci://registry-1.docker.io/bitnamicharts/postgresql
      setValues:
        auth:
          username: zyreva
          password: zyreva
          database: zyreva
portForward:
  - resourceType: service
    resourceName: zyreva-server
    port: 3000
