// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/zyreva/v1/zyreva.proto (package zyreva.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AnalyzeRequest, AnalyzeResponse } from "./zyreva_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service zyreva.v1.AppService
 */
export const AppService = {
  typeName: "zyreva.v1.AppService",
  methods: {
    /**
     * @generated from rpc zyreva.v1.AppService.Analyze
     */
    analyze: {
      name: "Analyze",
      I: AnalyzeRequest,
      O: AnalyzeResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

