apiVersion: v1
kind: Service
metadata:
  name: mibrel-server
  labels:
    app: mibrel-server
spec:
  ports:
  - port: 3000
    protocol: TCP
  clusterIP: None
  selector:
    app: mibrel-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mibrel-server
  labels:
    app: mibrel-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mibrel-server
  template:
    metadata:
      labels:
        app: mibrel-server
    spec:
      serviceAccountName: mibrel
      containers:
      - name: mibrel-server
        image: mibrel-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mibrel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mibrel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: mibrel
  namespace: default