apiVersion: v1
kind: Service
metadata:
  name: zyreva-server
  labels:
    app: zyreva-server
spec:
  ports:
  - port: 3000
    protocol: TCP
  clusterIP: None
  selector:
    app: zyreva-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zyreva-server
  labels:
    app: zyreva-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zyreva-server
  template:
    metadata:
      labels:
        app: zyreva-server
    spec:
      serviceAccountName: zyreva
      containers:
      - name: zyreva-server
        image: zyreva-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zyreva
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zyreva
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: zyreva
  namespace: default